import './globals.css'
import type { Metadata } from 'next'
import SessionProvider from '@/providers/SessionProvider'
import ToasterProvider from '@/providers/ToastProvider'
import Navbar from '@/components/navbar'


export const metadata: Metadata = {
    title: 'DashBoard',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <SessionProvider>
            <html lang="en">
                <body>
                    <ToasterProvider />
                    {children}
                </body>
            </html>
        </SessionProvider>
    )
}
